config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'archives/index'
  devise_for :users

  resources 'categories'
  resources 'entries'
  resources 'diet_plans'
  resources 'users', only: [:index]
  resources 'relationships', only: %i[index create destroy]
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/inbox'
end

app/models/diet_plan.rb
class DietPlan < ApplicationRecord
  belongs_to :user
  validates :calories, :proteins, :carbohydrates, :fats, presence: true
end

app/controllers/diet_plans_controller.rb
class DietPlansController < ApplicationController
  before_action :set_diet_plan, only: %i[edit update destroy show]

  def index
    @plan = current_user.diet_plan
  end

  def show
    @today_total = Entry.where(user_id: current_user.id)
                  .where('created_at >= ?', Date.today)
                  .select('SUM(calories) AS calories,SUM(proteins) AS Proteins ,SUM(carbohydrates) AS carbohydrates, SUM(fats) AS fats')
  end

  def new
    @plan = DietPlan.new
  end

  def create
    @plan = DietPlan.new(plan_params)
    @plan.user = current_user

    if @plan.save
      redirect_to diet_plans_path, notice: 'Your Diet Goal Set Successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to diet_plans_path, notice: 'Your Diet Goal Updated Successfully!'
    else
      render 'edit'
    end
  end

  private

  def set_diet_plan
    @plan = DietPlan.find(params[:id])
  end

  def plan_params
    params.require(:diet_plan).permit(:calories, :proteins, :carbohydrates, :fats)
  end
end

app/helpers/diet_plans_helper.rb
module DietPlansHelper
end

app/views/diet_plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(plan.errors.count, "error") %> found</p>
      </div>

      <div class="message-body">
        <ul>
          <% plan.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input", min: 0 %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/diet_plans/edit.html.erb
<% content_for :title do %>
  Edit Your Diet Goal
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <%= render 'form', plan: @plan %>
    </div>
</div>

app/views/diet_plans/index.html.erb
<% content_for :title do %>
  Your Daily Diet Goal
<% end %>

<div class="columns is-centered">
    <div class="column is-half">
        <div class="my-4">
            <% if @plan.present? %>
                <nav class="level is-mobile">
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">Calories</p>
                            <p class="title"><%= @plan.calories %></p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">Proteins</p>
                            <p class="title"><%= @plan.proteins %></p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">Carbohydrates</p>
                            <p class="title"><%= @plan.carbohydrates %></p>
                        </div>
                    </div>
                    <div class="level-item has-text-centered">
                        <div>
                            <p class="heading">Fats</p>
                            <p class="title"><%= @plan.fats %></p>
                        </div>
                    </div>
                </nav>

                <div class="columns">
                    <div class="column has-text-centered">
                        <%= link_to edit_diet_plan_path(@plan), class: "button is-primary" do %>
                            <svg width="20px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            <span class="ml-1">Edit Goal</span>
                        <% end %>
                    </div>
                </div>
                <div class="columns">
                    <div class="column has-text-centered ">
                        <%= link_to diet_plan_path(@plan), class: "button is-primary" do %>
                            <span class="mr-1">See Comparison</span>
                            <svg width="20px" viewBox="0 0 20 20" fill="white">
                                <path fill-rule="evenodd" d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11 4a1 1 0 10-2 0v4a1 1 0 102 0V7zm-3 1a1 1 0 10-2 0v3a1 1 0 102 0V8zM8 9a1 1 0 00-2 0v2a1 1 0 102 0V9z" clip-rule="evenodd" />
                            </svg>
                        <% end %>
                    </div>
                </div>
            <% else %>
                <div class="notification is-warning has-text-centered">
                    You haven't set your "Diet Goal" for one day.
                    <p>Setting a diet goal can encourage you to take care of your eating habit.</p>
                </div>

                <div class="columns">
                    <div class="column has-text-centered">
                        <%= link_to new_diet_plan_path, class: "button is-primary" do %>
                            <svg width="20px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                            <span class="ml-1">Set Goal</span>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/diet_plans/new.html.erb
<% content_for :title do %>
  Set Your Diet Goal
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <%= render 'form', plan: @plan %>
    </div>
</div>

app/views/diet_plans/show.html.erb
<% content_for :title do %>
  Comparison
<% end %>

<%# Goal Block Start %>
<div class="has-text-centered mb-4">
  <span class="has-text-weight-semibold is-size-4">Your Goal</span>
</div>

<div class="columns is-centered">
    <div class="column is-half">
        <div class="mb-5">
          <nav class="level is-mobile box">
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Calories</p>
                      <p class="title"><%= @plan.calories %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Proteins</p>
                      <p class="title"><%= @plan.proteins %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Carbohydrates</p>
                      <p class="title"><%= @plan.carbohydrates %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Fats</p>
                      <p class="title"><%= @plan.fats %></p>
                  </div>
              </div>
          </nav>
                
        </div>
    </div>
</div>
<%# Goal Block End %>

<%# Today Block Start %>
<div class="has-text-centered mb-4">
  <span class="has-text-weight-semibold is-size-4">Total Consumed Today</span>
</div>
<% unless @today_total[0].calories == nil %>
<div class="columns is-centered">
    <div class="column is-half">
        <div class="mb-5">
          <nav class="level is-mobile box">
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Calories</p>
                      <p class="title"><%= @today_total[0].calories %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Proteins</p>
                      <p class="title"><%= @today_total[0].proteins %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Carbohydrates</p>
                      <p class="title"><%= @today_total[0].carbohydrates %></p>
                  </div>
              </div>
              <div class="level-item has-text-centered">
                  <div>
                      <p class="heading">Fats</p>
                      <p class="title"><%= @today_total[0].fats %></p>
                  </div>
              </div>
          </nav>
                
        </div>
    </div>
</div>
<%# Today Block End %>

<%# Progress Bars Start %>
<div class="columns is-centered">
  <div class="column is-two-thirds">
    <div class="columns is-centered mb-0">
      <div class="column">
        <span>Calories</span>
        <% if @today_total[0].calories > @plan.calories %>
        <span class="tag is-warning">exceeded</span>
        <% end %>
      </div>
      <div class="column is-two-thirds">
        <progress class="progress is-primary" value="<%= @today_total[0].calories %>" max="<%= @plan.calories %>"></progress>
      </div>
    </div>
    <div class="columns is-centered mb-0">
      <div class="column">
        <span>Proteins</span>
        <% if @today_total[0].proteins > @plan.proteins %>
        <span class="tag is-warning">exceeded</span>
        <% end %>
      </div>
      <div class="column is-two-thirds">
        <progress class="progress is-primary" value="<%= @today_total[0].proteins %>" max="<%= @plan.proteins %>"></progress>
      </div>
    </div>
    <div class="columns is-centered mb-0">
      <div class="column">
        <span>Carbohydrates</span>
        <% if @today_total[0].carbohydrates > @plan.carbohydrates %>
        <span class="tag is-warning">exceeded</span>
        <% end %>
      </div>
      <div class="column is-two-thirds">
        <progress class="progress is-primary" value="<%= @today_total[0].carbohydrates %>" max="<%= @plan.carbohydrates %>"></progress>
      </div>
    </div>
    <div class="columns is-centered mb-5">
      <div class="column">
        <span>Fats</span>
        <% if @today_total[0].fats > @plan.fats %>
        <span class="tag is-warning">exceeded</span>
        <% end %>
      </div>
      <div class="column is-two-thirds">
        <progress
        class="progress is-primary"
        value="<%= @today_total[0].fats %>"
        max="<%= @plan.fats %>"
        >
        </progress>
      </div>
    </div>
  </div>
</div>
<%# Progress Bars End %>
<% else %>
  <div class="has-text-centered mb-4">
    <span class="is-size-6 is-italic">You haven't added any entry yet today.</span>
  </div>
<% end %>