config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'archives/index'
  devise_for :users

  resources 'categories'
  resources 'entries'
  resources 'diet_plans'
  resources 'users', only: [:index]
  resources 'relationships', only: %i[index create destroy]
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/inbox'
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, :category_id, presence: true

  belongs_to :user
  belongs_to :category

  def day
    created_at.strftime('%b %e, %Y')
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]
  before_action :owner_check, only: %i[edit update destroy]

  def index
    @pagy, @entries = pagy(Entry.where(user_id: current_user.id)
                                .where('created_at >= ?', Date.today), items: 4)
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user

    if params[:back]
      render :new
    elsif @entry.save
      redirect_to entries_path, notice: 'Entry saved.'
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @entry.destroy

    redirect_to entries_path, notice: 'Entry deleted.'
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
  end

  def owner_check
    return unless current_user != @entry.user

    flash[:alert] = 'You can only edit or delete your own entries'
    redirect_to @entry
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> found</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :meal_type, class: "label" %>
    <%= form.text_field :meal_type, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :calories, class: "label" %>
    <%= form.number_field :calories, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :proteins, class: "label" %>
    <%= form.number_field :proteins, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :carbohydrates, class: "label" %>
    <%= form.number_field :carbohydrates, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :fats, class: "label" %>
    <%= form.number_field :fats, class: "input", min: 0 %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: "label" %>
    <div class="select">
      <%= form.select :category_id, Category.where(user_id: current_user.id).collect {|u| [u.title, u.id]} %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :title do %>
  Edit Entry : <%= @entry.meal_type %>
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Meal Records &ndash; <%= DateTime.now.to_s(:nice_date) %>
<% end %>

<div class="columns is-centered mt-6 mb-4">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            <%= entry.meal_type %>
            <span class="tag ml-2 is-dark is-size-7"><%= entry.category.title if entry.category.present? %></span>
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <% if entry.calories %>
            <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
            <% end %>
            <% if entry.proteins %>
            <p><span class="has-text-weight-bold"><%= entry.proteins %></span> g (proteins)</p>
            <% end %>
            <% if entry.carbohydrates %>
            <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> g (carbohydrates)</p>
            <% end %>
            <% if entry.fats %>
            <p><span class="has-text-weight-bold"><%= entry.fats %></span> g (fat)</p>
            <% end %>
            <p class="is-size-7"><%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>

        <div class="card-footer">
          <%= link_to 'Show', entry, class: "card-footer-item" %>
          <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="columns is-centered mb-0">
  <div class="column is-one-quarter">
    <%== render partial: 'pagy/bulma_nav', locals: {pagy: @pagy} %>
  </div>
</div>


<div class="columns is-centered my-4">
  <%= link_to "View All Entries", archives_index_path, class: "button is-primary is-outlined" %>
</div>

app/views/entries/new.html.erb
<% content_for :title do %>
  Add Entry
<% end %>

<% if Category.where(user_id: current_user.id).count.zero? %>
  <div class="columns is-centered">
    <div class="column is-one-third">
      <div class="notification is-danger is-light animated fadeIn has-text-centered">
        <%= link_to "Add", new_category_path, class: "is-link" %> Some Categories First!
      </div>
    </div>
  </div>
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <%= render 'form', entry: @entry %>
    </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.meal_type %> &ndash; <%= @entry.created_at.to_s(:nice_date) %>

<% end %>

<div class="columns mt-3 is-centered">
  <div class="column is-one-third">
    <nav class="panel is-primary">
      <p class="panel-heading">
        <%= @entry.meal_type %>
        <% if @entry.category.present? %>
          <span class="tag is-light">
          <%= @entry.category.title %>
          </span>
        <% end %>
      </p>
      
      <div class="panel-block">
        Calories: <%= @entry.calories %>
      </div>

      <div class="panel-block">
        Proteins: <%= @entry.proteins %>
      </div>

      <div class="panel-block">
        Carbohydrates: <%= @entry.carbohydrates %>
      </div>

      <div class="panel-block">
        Fats: <%= @entry.fats %>
      </div>
    </nav>
    <% if current_user == @entry.user %>
    <div class="columns is-mobile">
      <div class="column">
        <%= link_to 'Edit', edit_entry_path(@entry), class: "button is-gray" %>
        <%= link_to 'Delete', entry_path(@entry), method: :delete, data: { confirm: "Are you sure?" }, class: "button is-gray" %>
      </div>
    </div>
    <% end %>
</div>
</div>