config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'archives/index'
  devise_for :users

  resources 'categories'
  resources 'entries'
  resources 'diet_plans'
  resources 'users', only: [:index]
  resources 'relationships', only: %i[index create destroy]
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/inbox'
end

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <span class="has-text-weight-bold is-size-4 ml-4">MealDiary</span>
    <% end %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarMenu" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to root_path, class: "navbar-item" do %>
        <svg width="17px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
        </svg>
        <span class="ml-1">Home</span>
      <% end %>
            
      <%= link_to  diet_plans_path, class: "navbar-item" do %>
        <svg width="17px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
        </svg>
        <span class="ml-1">Daily Goal</span>
      <% end %>
      
      <%= link_to new_entry_path, class: "navbar-item" do %>
        <svg width="17px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span class="ml-1">Add Entry</span>
      <% end %>

      <%= link_to  users_path, class: "navbar-item" do %>
        <svg width="17px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0" stroke-opacity="0.8">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
        </svg>
        <span class="ml-1">Users</span>
      <% end %>
      
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Categories
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Add New", new_category_path, class: "navbar-item" %>
          <%= link_to "View All", categories_path, class: "navbar-item" %>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      
      <% if user_signed_in? %>
      <figure class="image is-48x48">
        <%= image_tag(current_user.image.url, class: 'is-rounded') %>
      </figure>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
        <span class="has-text-weight-bold is-size-6">Welcome, <%= current_user.username.capitalize %></span>
        </a>

        <div class="navbar-dropdown">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item pr-0" %>
          <%= link_to "Check Mails", '/inbox', class: "navbar-item pr-0", target: "_blank" %>
          <%= link_to "View Today Entries", entries_path, class: "navbar-item pr-0" %>
          <%= link_to "View Archives", archives_index_path, class: "navbar-item pr-0" %>
        </div>
      </div>
      <% end %>

      <div class="navbar-item">
        <div class="buttons">
        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete, class: "button is-primary" do %>
            <strong class="mr-1">Sign Out</strong>
            <svg width="17px" viewBox="0 0 24 24" stroke="currentColor" fill-opacity="0">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
            </svg>
          <% end %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path, class: "button is-light" %>
          <%= link_to new_user_session_path, class: "button is-primary" do %>
            <strong>Log In</strong>
          <% end %>
        <% end %>
        </div>
      </div>
      
    </div>
  </div>
</nav>
<section class="hero is-primary is-small">

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
            <%= yield :title %>
        <% else %>
            Meal Diary
        <% end %>
      </h1>
    </div>
  </div>
</section>