config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'archives/index'
  devise_for :users

  resources 'categories'
  resources 'entries'
  resources 'diet_plans'
  resources 'users', only: [:index]
  resources 'relationships', only: %i[index create destroy]
  root 'home#index'
  mount LetterOpenerWeb::Engine, at: '/inbox'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  has_many :entries, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :owner_check, only: %i[edit update destroy]

  def index
    @categories = Category.where(user_id: current_user.id)
  end

  def show 
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    if params[:back]
      render :new
    elsif @category.save
      redirect_to categories_path, notice: 'Category saved.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path, notice: 'Category deleted.'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end

  def owner_check
    return unless current_user.id != @category.user_id

    flash[:alert] = 'You can only edit or delete your own categories'
    redirect_to @category
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div class="message is-danger">
      <div class="message-header">
        <h2><%= pluralize(category.errors.count, "error") %> found</h2>
      </div>

      <div class="message-body">
        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit class: "button is-primary mt-3" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title do %>
  Edit Category : <%= @category.title %>
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <h3 class="is-size-3 has-text-weight-bold mb-3">Edit Category</h3>
        <%= render 'form', category: @category %>
    </div>
</div>

app/views/categories/index.html.erb
<% content_for :title do %>
  Categories
<% end %>

<div class="columns is-centered mt-3">
    <div class="column is-half">
        <table class="table is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Title</th>
              <th class="has-text-centered" colspan="2">Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.title %></td>
                <td class="has-text-centered"><%= link_to 'Edit Item', edit_category_path(category) %></td>
                <td class="has-text-centered"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title do %>
  Add Category
<% end %>

<div class="columns is-centered">
    <div class="column is-one-third">
        <%= render 'form', category: @category %>
    </div>
</div>